version: '3.9'

volumes:
  django_postgres:
    name: django_postgres
  django_rabbitmq:
    name: django_rabbitmq

services:
  postgres:
    container_name: config_postgres
    hostname: postgres.django.com
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - django_postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  rabbitmq:
    container_name: config_rabbitmq
    hostname: rabbitmq.django.com
    image: rabbitmq:latest
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - django_rabbitmq:/var/lib/rabbitmq

  django:
    container_name: config_django
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command:
      - bash
      - -c
      - |
        python manage.py migrate --noinput
        python manage.py collectstatic --no-input
        python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq

  celery_beat:
      container_name: config_celery_beat
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - .env
      command: celery -A config.celery:app beat -l INFO
      depends_on:
        - postgres
        - rabbitmq

  celery_worker:
      container_name: config_celery_worker
      build:
        context: .
        dockerfile: Dockerfile
      env_file:
        - .env
      command: celery -A config.celery:app worker -l INFO
      depends_on:
        - postgres
        - rabbitmq
