# Generated by Django 4.2.9 on 2024-02-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paymet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymet',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
