# Generated by Django 4.2.9 on 2024-02-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0002_auto_is_publish_auto_title_auto_total_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='is_publish',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='total_views',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='auto',
            name='brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='auto',
            name='end_auction_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='auto',
            name='mileage',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='auto',
            name='reference_number',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='auto',
            name='registration_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='auto',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
