# Generated by Django 4.2.9 on 2024-03-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auto', '0003_remove_auto_created_at_remove_auto_is_publish_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='end_auction_date',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='mileage',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='reference_number',
        ),
        migrations.RemoveField(
            model_name='auto',
            name='registration_date',
        ),
        migrations.AlterField(
            model_name='auto',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
